name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, xml, curl, mysql

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run tests
      run: php artisan test

    - name: Deploy to AWS CodeDeploy
      uses: aws-actions/aws-codedeploy-github-actions@v1.0.4
      with:
        application-name: laravel
        deployment-group-name: laravelproject
        deployment-config-name: CodeDeployDefault.OneAtATime
        github-token: ${{ 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 }}
        region: us-west-2
