name: Deploy to Development

on:
  push:
    branches:
      - master  # Trigger the workflow only on push to the master branch

jobs:
  composer_development:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: composer install

  npm_development:
    runs-on: self-hosted
    needs: composer_development

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm install

  create_env_file:
    runs-on: self-hosted
    needs: npm_development

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Retrieve LARAVEL_ENV from Parameter Store
      id: ssm
      run: |
        LARAVEL_ENV=$(aws ssm get-parameter --name "laravel_env" --query "Parameter.Value" --output text)
        echo "LARAVEL_ENV=$LARAVEL_ENV" >> $GITHUB_ENV

    - name: Create .env file
      run: |
        echo "APP_ENV=PROD" > .env
        echo "LARAVEL_ENV=${{ env.LARAVEL_ENV }}" >> .env
        # Add more environment variables as needed

  zip_application:
    runs-on: self-hosted
    needs: create_env_file

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create deployment package
      run: |
        zip -r laravel.zip .  # Create a ZIP file of the application

  upload_to_s3:
    runs-on: self-hosted
    needs: zip_application

    steps:
    - name: Upload ZIP to S3
      run: |
        aws s3 cp laravel.zip s3://elson-testing/app/laravel.zip --region us-east-2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_development:
    runs-on: self-hosted
    needs: upload_to_s3 #elson-testing

    steps:
    - name: Create a new deployment
      run: |
        aws deploy create-deployment \
          --application-name laravel \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name laravelproject \
          --s3-location bucket=elson-testing,key=app/laravel.zip,bundleType=zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
